import { IsBoolean, IsNotEmpty, IsNumber, IsString } from 'class-validator';

export class BahnOrderResponseDTO {
  /** Order index returned by Bahn */
  @IsNumber()
  orderIndex: number;

  /** Order number generated by Bahn */
  @IsString()
  @IsNotEmpty()
  orderNumber: string;

  /** Indicates if the order was successfully created */
  @IsBoolean()
  success: boolean;
}
