import { Type } from 'class-transformer';
import {
  IsArray,
  IsBoolean,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
  ValidateNested,
} from 'class-validator';

export class BahnOrderResponseDto {
  /** Order index returned by Bahn */
  @IsNumber()
  orderIndex: number;

  /** Order number generated by Bahn */
  @IsString()
  @IsNotEmpty()
  orderNumber: string;

  /** Indicates if the order was successfully created */
  @IsBoolean()
  success: boolean;

  /** Array of errors (only present when success is false) */
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => BahnOrderErrorDto)
  errors?: BahnOrderErrorDto[];
}

export class BahnOrderErrorDto {
  /** Order index from error */
  @IsNumber()
  orderIndex: number;

  /** Order number from error */
  @IsString()
  @IsNotEmpty()
  orderNumber: string;

  /** Error message */
  @IsString()
  @IsNotEmpty()
  error: string;
}
