import {
  IsDateString,
  IsNotEmpty,
  IsOptional,
  IsString,
} from 'class-validator';

export class BahnOrderResponseDto {
  /** Order ID generated by Bahn */
  @IsString()
  @IsNotEmpty()
  id: string;

  /** External reference ID */
  @IsString()
  @IsNotEmpty()
  externalId: string;

  /** Order status */
  @IsString()
  @IsNotEmpty()
  status: string;

  /** Creation timestamp */
  @IsDateString()
  createdAt: string;

  /** Update timestamp */
  @IsDateString()
  updatedAt: string;

  /** Order number */
  @IsString()
  @IsNotEmpty()
  orderNumber: string;

  /** Additional message from API */
  @IsOptional()
  @IsString()
  message?: string;
}
