version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: order-integrator-rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - order-integrator-network

volumes:
  rabbitmq_data:
    driver: local

networks:
  order-integrator-network:
    driver: bridge 